name: Manual Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to the main '
        required: true
        default: 'staging'
      enableFeatureX:
        description: 'Enable feature X'
        required: false
        type: 'boolean'
        default: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print input values
        run: |
          echo "Deploying to environment to it : ${{ github.event.inputs.environment }}"
          echo "Enable Feature X: ${{ github.event.inputs.enableFeatureX }}"

      - name: Conditional step for Feature X
        if: ${{ github.event.inputs.enableFeatureX == 'true' }}
        run: |
          echo "Feature X is enabled!"
          # Add commands to handle Feature X here
